### ISSUE TITLE
Error: Cannot find module 'c:\Program Files\Microsoft VS Code\resources\app\node_modules\spdlog\build\spdlog.node'

### ISSUE THREAD

**Issue by murnana** [murnana/vscode-eslint#1]
``` log
Error: Cannot find module 'c:\Program Files\Microsoft VS Code\resources\app\node_modules\spdlog\build\spdlog.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (c:\Program Files\Microsoft VS Code\resources\app\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules\spdlog\index.js:3:35)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules\spdlog\index.js:21:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by murnana** [comment]
Python 2.7インストール後
```log
MSBUILD : error MSB3428: Visual C++ コンポーネント "VCBuild.exe" を読み込めませんでした。この問題を解決するには、次のいずれかを行ってください。 1) .NET Framework 2.0 SDK インストールする。 2) Microsoft Visual Studio 2005 をインストールする。 3) その他の場所にインスト
ールされている場合、コンポーネントの場所をシステム パスに追加する。 [project\full\path\vscode-eslint\nod
e_modules\spdlog\build\binding.sln]
```

**Comment by murnana** [comment]
1. .NET Framework 2.0 SDK インストールする
2. Microsoft Visual Studio 2005 再配布パッケージ をインストール
3. VCBuild.exeとVC++のincludeの場所をシステム パスに追加
```log
node\js\path\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(16): fatal error C1083
: include ファイルを開けません。'windows.h': No such file or directory [project\path\vscode-eslint\node_modules\spdlog\build\bindin
g.sln]
project\path\vscode-eslint\node_modules\nan\nan.h(47): fatal error C1189: #error :  This version of node/NAN/v8 requires
 a C++11 compiler [project\path\vscode-eslint\node_modules\spdlog\build\binding.sln]
project\path\Dropbox\vscode-eslint\node_modules\nan\nan.h(47): fatal error C1189: #error :  This version of node/NAN/v8 requires
 a C++11 compiler [project\path\vscode-eslint\node_modules\spdlog\build\binding.sln]
```
